### ISSUE TITLE
retrain Classifier for CO1 custom data

### ISSUE THREAD

**Issue by mbenucci** [terrimporter/CO1Classifier#1]
Dear Dr. Porter,

I've been trying to retrain the RDPClassifier to be used for a custom database on CO1; and starting from your trained dataset as a baseline I've moved towards retraining using just my custom data. I've realised that I'm currently missing any documentation regarding the construction of the "gene_copynumber" file that should be used in the last steps of retraining the classifier. Is there any documentation available on the topic?

Thanks in advance,
Marco

**Comment by terrimporter** [comment]
I did not use a gene_copynumber file for training, this is optional for the RDP classifier and you should still be able to retrain your classifier without it.

FYI, I've updated the CO1 reference set to v3 in case you find it useful.

**Comment by mbenucci** [comment]
That's fantastic, thanks a lot. I will check the new version of the training as well then.
