### ISSUE TITLE
Which trained files to use for classification with RDP classifier?

### ISSUE THREAD

**Issue by naurasd** [terrimporter/CO1Classifier#3]
Hey guys,

I wanted to use your train dataset (V4) to taxonomically assign my sequences in dada2 using the RDP classifier. I am a bit confused though on how to actually do this with the files provided in the trained tar.gz directory.

I have unzipped the CO1v4_trained.tar.gz but there is no fasta file with reference sequences. Isn't that what is needed as input for the RDP classifier? The genus_wordConditionalProbList.txt file is a pretty large file so I am pretty sure this one is being used for the actual taxonomic classification, I just don't know how exactly.

I have the feeling I totally misunderstand how your datasets are being used with the RDP classifier, sorry for that. Your help is much appreciated.

Cheers
Nauras

**Comment by girouxem** [comment]
I have the same question ...

**Comment by terrimporter** [comment]
Sorry for the late response.  I've added a 'quickstart' to the main page to help get the classifier installed and running.

**Comment by naurasd** [comment]
thanks, appreciate it.
