### ISSUE TITLE
A newer version of the database is available?

### ISSUE THREAD

**Issue by Anto007** [terrimporter/CO1Classifier#4]
I was wondering if a newer version of your database is going to be made available anytime soon? The v4 seems to contain sequences only up until 2019?

**Comment by terrimporter** [comment]
COVID has delayed all the work I do on the side.  There is a new version that is partially assembled but probably won't be released until the new year (2022).  Thanks for your understanding.

**Comment by terrimporter** [comment]
@Anto007 the new v5 version is now available.  Validation is running in the background and I'll update the recommended cutoff values as I get them as it takes a while to run.
