### ISSUE TITLE
add Homo sapiens COI seqs?

### ISSUE THREAD

**Issue by anslan** [terrimporter/CO1Classifier#5]
Would it be possible to add Homo sapiens COI seqs in the following releases? Would be very useful to detect human "contamination"

**Comment by Anto007** [comment]
I too think _H. sapiens_ will be a useful addition to the next release. At the moment, while using the current database release, _H. sapiens_ COI sequence is somehow being classified by RDP Classifier as wedge-tailed eagle (_Aquila audax_) at a bootstrap cutoff value of 0.99 :-)

**Comment by terrimporter** [comment]
Good idea, I will add a few back to the next version.

**Comment by Anto007** [comment]
@terrimporter May I know when a new version of the database can be expected? I of course realize this is something that you do on the side. Thank you for your initiative.

**Comment by terrimporter** [comment]
@Anto007 I've just added updated v5 COI reference databases trained for either the RDP Classifier, BLAST (new), or SINTAX (new).

**Comment by terrimporter** [comment]
@anslan and @Anto007 the new v5 version should also contain some Homo sapiens sequences in addition to the bacterial outgroup sequences
